import cookieParser from 'cookie-parser';
import cors from 'cors';
import e from 'express';
import { limiter, speedLimiter, WHITELIST_DOMAINS } from './constants.js';
import errorHandler from './middlewares/errorhandler.middleware.js';
import healthCheckRouter from './routes/healthCheck.route.js';
import userRouter from './routes/user.route.js';

const app = e();
app.use(e.json());
app.use(e.urlencoded({ extended: true }));
app.use(e.static('public'));
app.use(cors({ origin: WHITELIST_DOMAINS, credentials: true }));
app.use(cookieParser());
app.use(speedLimiter);
app.use(limiter);
app.use('/api/v1', healthCheckRouter);
app.use('/api/v1/users', userRouter);
app.use(errorHandler);
export { app };
